spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      default-filters:
        - CorsFilter
        - PreserveHostHeader=True
      routes:
        ## service1
        - id: modular-monolith
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2


server:
  port: 8080