spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: modular-monolith
          uri: https://cse-modular-monolith.azurewebsites.net/
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthHeaderFilter


server:
  port: 8081